config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Static Pages
  get "/landing",   to: "pages#landing"
  get "/dashboard", to: "pages#dashboard"

  # Devise
  # devise_for :users

  # Chats
  # get  "/chats",          to: "chats#index"
  # get  "/chats/new",      to: "chats#new"
  # get  "/chats/:id",      to: "chats#show"
  # post "/chats",          to: "chats#create"

  resources :chats, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end


  # Messages inside a chat
  #  post "/chat/:id/messages", to: "chats#create"

  # Recipes
  # get    "/recipes",     to: "recipes#index"
  # get    "/recipes/:id", to: "recipes#show"
  # delete "/recipes/:id", to: "recipes#destroy"

  resources :recipes, only: [:index, :destroy, :show]

  resources :messages, only: [] do
    resources :recipes, only: [:new, :create]
  end
end

app/views/pages/home.html.erb
<div class="land-page">

  <%# Sidebar %>
  <% if user_signed_in? %>
    <div data-controller="sidebar">
      <div class="sidebar" data-sidebar-target="panel">
        <%= link_to root_path, class: "sidebar-img" do %>
          <%= image_tag "fridgeogo.png" %>
        <% end %>

        <h1 class="sidebar-text"> Saved Recipes</h1>

        <% @recipes.each do |recipe| %>
          <%= link_to recipe.title, recipe_path(recipe), class: "sidebar-btn recipe" %><br>
        <% end %>

      </div>

      <div class="sidebar-toggle" data-action="click->sidebar#toggle">
        <i class="fa-solid fa-chevron-right"></i>
      </div>

    </div>
  <% end %>

  <%# Banner %>


  <div class="<%= user_signed_in? ? 'bannerin' : 'bannerout' %>">

    <div class="banner-inner">
      <% if user_signed_in? %>
        <h3>Welcome back <%= current_user.username %></h3>
        <h1>What are we cooking today?</h1>

        <a
          data-controller="rotate"
          data-rotate-recipes-value="<%= @recipes.map { |r| [r.title, recipe_path(r)] }.to_json %>"
          class="rotating-text sidebar-btn recipe">
        </a>

      <% else %>
        <h1>AI Recipe Finder</h1>
        <p>Tell the AI your ingredients — get an instant recipe.</p>
        <%= link_to "Sign in", new_user_session_path, class: "my-button" %>
        <%= link_to "Sign up", new_user_registration_path, class: "my-button" %>
      <% end %>
    </div>

  </div>


  <%# Cards %>
  <% if user_signed_in? %>
    <div class="cards">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)), url(https://alis.alberta.ca/media/697297/cook.jpg?width=830&height=510&v=1d4acf1f5493b20)">
        <%= link_to new_chat_path, class: "card-link" do %>
          AI Cook
        <% end %>
      </div>
    </div>
  <% end %>

  </div>