config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Static Pages
  get "/landing",   to: "pages#landing"
  get "/dashboard", to: "pages#dashboard"

  # Devise
  # devise_for :users

  # Chats
  # get  "/chats",          to: "chats#index"
  # get  "/chats/new",      to: "chats#new"
  # get  "/chats/:id",      to: "chats#show"
  # post "/chats",          to: "chats#create"

  resources :chats, only: [:index, :new, :show, :create] do
    resources :messages, only: [:create]
  end


  # Messages inside a chat
  #  post "/chat/:id/messages", to: "chats#create"

  # Recipes
  # get    "/recipes",     to: "recipes#index"
  # get    "/recipes/:id", to: "recipes#show"
  # delete "/recipes/:id", to: "recipes#destroy"

  resources :recipes, only: [:index, :destroy, :show]

  resources :messages, only: [] do
    resources :recipes, only: [:new, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AiAssistant</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= user_signed_in? ? 'logged-in' : 'logged-out' %>">
    <% unless devise_controller? %>
      <div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
        <div class="container-fluid">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag "fridgeogo.png" %>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Cookbook", recipes_path, class: "nav-link text-white" %>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-white" href="#" data-bs-toggle="offcanvas" data-bs-target="#chatsOffcanvas" aria-controls="chatsOffcanvas">Chats</a>
                </li>
                <li class="nav-item ms-2">

                  <%= link_to "New Chat", new_chat_path, class: "nav-link text-white" %>
                </li>

                <li class="nav-item dropdown ms-3">
                  <%= image_tag "https://cdn-icons-png.flaticon.com/512/219/219983.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Sign in", new_user_session_path, class: "nav-link text-white" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="container">
    <% end %>
      <%= yield %>
    </div>
    <%= render 'shared/offcanvas' if user_signed_in? %>

  </body>
</html>